尝试一下pull request
TheresaQWQ/SuperBot pull request #1
Opened 2020-09-16 17:08 UTC by shitianshiwa

2020-09-16 23:29 UTC, shitianshiwa commented
版本差异大，放弃pull request

2020-09-20 02:59 UTC, TheresaQWQ requested changes
1. 此程序需要兼容Linux，建议去掉bat文件
2. 不要为某一个插件单独新建一个lib，尽量把lib做的所有插件都能用，然后直接挂到api上
3. 不要过度使用代码格式化工具，你的一堆File changed都是代码格式化插件产生的

2020-09-20 04:07 UTC, shitianshiwa commented
> 1. 此程序需要兼容Linux，建议去掉bat文件
> 2. 不要为某一个插件单独新建一个lib，尽量把lib做的所有插件都能用，然后直接挂到api上
> 3. 不要过度使用代码格式化工具，你的一堆File changed都是代码格式化插件产生的

1、也要给windows平台提供便利
2、lib那个我试着整合进插件里
3、。。。我不知道咋解决

2020-09-20 06:14 UTC, shitianshiwa commented
修改一下另一个吧。。

2020-09-20 06:14 UTC, closed without merging